### PR TITLE
fix(fmt): fix formatting for trailing comment after the last field

### LINKED ISSUE #2909: Formatting duplicates fields
```tact
struct RequestBody {
    field: Address;
    // Other data fields...
}
```
I guess it is the minimal possible example

### PR DESCRIPTION
**Pull request by i582**
## Issue

Closes #2909.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

File: src/fmt/formatter/format-structs.ts [hunk 1]
```diff
@@ -115,9 +115,9 @@ const formatFields: FormatRule = (code, node) => {
 
                 if (field.type === "Comment") {
                     if (needNewline) {
-                        code.add(" ");
+                        code.newLine();
                     }
-                    code.apply(formatComment, child);
+                    code.apply(formatComment, field);
```
Comment (novusnota) [inline src/fmt/formatter/format-structs.ts:120]: 436159020-7eecb501-91c6-4a89-9983-38884a536b08

**Review by novusnota — APPROVED** [review]
