### PR TITLE
fix: better error message for `Slice? as remaining`

### LINKED ISSUE #2674: Internal Compiler Error When Using `Slice? as remaining` in Struct
Declaring a struct with an optional `Slice` field marked `as remaining` causes an **internal compiler error**, despite no documentation indicating that this usage is invalid.

---

### Minimal Reproducible Example

```tact
struct OptRem {
    tail: Slice? as remaining;
}
```

---

### Actual Behavior

The compiler crashes with:

```
[INTERNAL COMPILER ERROR]: "as remaining" cell cannot be optional
```

This is a hard crash, not a user-facing compile-time error.

---

### Expected Behavior

- The documentation explains that a `remaining` field must be the **last field** in a struct and only one is allowed.
- It does **not state** that `remaining` fields **must not be optional**.
- Optionals are generally allowed in structs and for `Slice` types.
- The compiler should either support this or reject it cleanly with a proper error message.

---

### Why This Is a Problem

- There is **no documented restriction** against using `?` on a `remaining` field.
- The placement is correct (last field, single occurrence).
- An internal compiler error indicates a missing safety check in the compiler.
- This breaks the language's guarantees about robustness and developer feedback.

---

### Conclusion

This is a confirmed **internal compiler bug and documentation gap**. If `Slice? as remaining` is unsupported, the compiler should provide a proper error — not crash. If it's intended to be supported, it must be fixed to compile successfully. Either way, the current behavior is incorrect.

---

LLM Fuzzing discovery (see #2490)

### PR DESCRIPTION
**Pull request by i582**
## Issue

Closes #2674.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

File: src/types/resolveSignatures.ts [hunk 1]
```diff
@@ -217,6 +217,17 @@ export function resolveSignatures(ctx: CompilerContext, Ast: FactoryAst) {
             }
         }
 
+        const lastField = t.fields.at(-1);
```
Comment (anton-trunov) [inline src/types/resolveSignatures.ts]: Wait, let's actually ban it for any field, not just the last one

**Review by anton-trunov — CHANGES_REQUESTED** [review]

File: src/types/resolveSignatures.ts (hunk 1 above)
Comment (i582) [reply src/types/resolveSignatures.ts]: If you write `Slice? as remaining` not in the last field, compiler will give an error already

Comment (i582) [reply src/types/resolveSignatures.ts]:
```
Error: test/main.tact:75:5: The "as remaining" field can only be the last field of the message
  74 | message Name {
> 75 |     bar: Slice? as remaining;
           ^~~~~~~~~~~~~~~~~~~~~~~~
  76 |     foo: Int;
```

Comment (i582) [reply src/types/resolveSignatures.ts]: So, it is enough to check only the last field :)

Comment (anton-trunov) [reply src/types/resolveSignatures.ts]: > If you write Slice? as remaining not in the last field, compiler will give an error already

We might re-enable using `as remaining` anywhere, it's actually can be quite useful

Comment (anton-trunov) [reply src/types/resolveSignatures.ts]: Also, this makes this check orthogonal which is good from the design prospective

Comment (i582) [reply src/types/resolveSignatures.ts]: Done

**Review by anton-trunov — APPROVED** [review]
