### PR TITLE
fix: do not double check message opcodes

### LINKED ISSUE #1556: Stop checking message opcodes after it's been already parsed in router
That is how it looks like in out final code
```
DUP
PUSHINT 395134233
EQUAL
IFJMP:<{
  DROP
  LDU 32
  SWAP
  PUSHINT 395134233
  EQUAL
  THROWIFNOT 129
```

Which is useless. Each check is done twice and we spend gas on quite a few instructions

### LINKED ISSUE #1669: External fallback receiver does not get generated
Test case:
```tact
contract Test {
    external(msg: Slice) { }
}
```

Error message:
```
Function '~$Test$_external_any' does not exist in imported FunC sources
```

### PR DESCRIPTION
**Pull request by anton-trunov**
## Issue

Closes #1556.

It also loads or pre-loads the message opcode depending on the existence of a fallback receiver.

## Notes

It seems some Escrow receivers started consuming more gas because of the changes in how code is packed. Just in case, here is the OLD and NEW Fift code for Escrow: https://gist.github.com/anton-trunov/0154860361636dbbcfbd0d1316b53da9.

#### funding 1
| Instruction       | Before# | After# | Δ# | Before$ | After$ |   Δ$ |
| ----------------- | -------:| ------:| --:| -------:| ------:| ----:|
| `Total`           |      62 |     65 | +3 |    1336 |   1374 |  +38 |
| `implicit JMPREF` |       0 |      1 | +1 |       0 |    110 | +110 |
| `PUSHCONT`        |      18 |     20 | +2 |     348 |    400 |  +52 |
| `LDU`             |       3 |      4 | +1 |      78 |    104 |  +26 |
| `SWAP`            |      16 |     17 | +1 |     288 |    306 |  +18 |
| `IFJMP`           |       4 |      5 | +1 |      72 |     90 |  +18 |
| `IFELSE`          |       6 |      7 | +1 |     108 |    126 |  +18 |
| `DUP`             |       9 |      8 | -1 |     162 |    144 |  -18 |
| `IFJMPREF`        |       2 |      1 | -1 |      52 |     26 |  -26 |
| `PLDU`            |       3 |      2 | -1 |     102 |     68 |  -34 |
| `IFREFELSE`       |       1 |      0 | -1 |     126 |      0 | -126 |

#### changeCode 1
| Instruction  | Before# | After# | Δ# | Before$ | After$ |   Δ$ |
| ------------ | -------:| ------:| --:| -------:| ------:| ----:|
| `Total`      |      25 |     20 | -5 |     555 |    428 | -127 |
| `DUP`        |       6 |      5 | -1 |     108 |     90 |  -18 |
| `EQUAL`      |       2 |      1 | -1 |      36 |     18 |  -18 |
| `PUSHINT`    |      12 |     11 | -1 |     241 |    218 |  -23 |
| `PLDU`       |       3 |      2 | -1 |     102 |     68 |  -34 |
| `THROWIFNOT` |       2 |      1 | -1 |      68 |     34 |  -34 |

#### approve 1
| Instruction       | Before# | After# | Δ# | Before$ | After$ |   Δ$ |
| ----------------- | -------:| ------:| --:| -------:| ------:| ----:|
| `Total`           |      77 |     80 | +3 |    1714 |   1752 |  +38 |
| `implicit JMPREF` |       0 |      1 | +1 |       0 |    110 | +110 |
| `PUSHCONT`        |      22 |     24 | +2 |     420 |    472 |  +52 |
| `LDU`             |       3 |      4 | +1 |      78 |    104 |  +26 |
| `SWAP`            |      23 |     24 | +1 |     414 |    432 |  +18 |
| `IFJMP`           |       4 |      5 | +1 |      72 |     90 |  +18 |
| `IFELSE`          |       8 |      9 | +1 |     144 |    162 |  +18 |
| `DUP`             |      10 |      9 | -1 |     180 |    162 |  -18 |
| `IFJMPREF`        |       3 |      2 | -1 |     178 |    152 |  -26 |
| `PLDU`            |       3 |      2 | -1 |     102 |     68 |  -34 |
| `IFREFELSE`       |       1 |      0 | -1 |     126 |      0 | -126 |

#### approve 2
No diff

#### approve 3
No diff

#### cancel 1
| Instruction       | Before# | After# | Δ# | Before$ | After$ |   Δ$ |
| ----------------- | -------:| ------:| --:| -------:| ------:| ----:|
| `Total`           |      77 |     80 | +3 |    1830 |   1868 |  +38 |
| `implicit JMPREF` |       1 |      2 | +1 |     110 |    220 | +110 |
| `PUSHCONT`        |      22 |     24 | +2 |     436 |    488 |  +52 |
| `LDU`             |       3 |      4 | +1 |      78 |    104 |  +26 |
| `SWAP`            |      20 |     21 | +1 |     360 |    378 |  +18 |
| `IFJMP`           |       4 |      5 | +1 |      72 |     90 |  +18 |
| `IFELSE`          |       8 |      9 | +1 |     144 |    162 |  +18 |
| `DUP`             |      11 |     10 | -1 |     198 |    180 |  -18 |
| `IFJMPREF`        |       4 |      3 | -1 |     204 |    178 |  -26 |
| `PLDU`            |       3 |      2 | -1 |     102 |     68 |  -34 |
| `IFREFELSE`       |       1 |      0 | -1 |     126 |      0 | -126 |

#### cancel 2
No diff

## Checklist

- [x] I have added tests to demonstrate the contribution is correctly implemented: it reduces gas consumption for the common cases, makes storage improvements, etc. and does not have too much negative impact for the rest of the use-cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/generator/writers/writeRouter.ts [hunk 1]
```diff
@@ -7,284 +7,458 @@ import { ops } from "./ops";
...
+        );
 
-            ctx.append("return (self, true);");
-        } else {
-            ctx.append();
-            ctx.append("return (self, false);");
+    wCtx.append(`;; Bounced handler for ${selector.type} message`);
+    const allocation = getType(wCtx.ctx, selector.type);
+    wCtx.append(`if (op == ${messageOpcode(allocation.header!)}) {`);
+    wCtx.inIndent(() => {
```
Comment (anton-trunov) [inline src/generator/writers/writeRouter.ts]: `wCtx.inIndent` -> `wCtx.inBlock`

File: src/generator/writers/writeRouter.ts [hunk 2]
```diff
@@ -7,284 +7,458 @@ import { ops } from "./ops";
...
+    throwCompilationError,
+    throwInternal,
+    throwInternalCompilerError,
+} from "../../error/errors";
+import type { SrcInfo } from "../../grammar";
+
+type ContractReceivers = {
+    internal: Receivers;
+    external: Receivers;
+    bounced: BouncedReceivers;
```
Comment (anton-trunov) [inline src/generator/writers/writeRouter.ts:21]:
```suggestion
    readonly internal: Receivers;
    readonly external: Receivers;
    readonly bounced: BouncedReceivers;
```

File: src/generator/writers/writeRouter.ts [hunk 3]
```diff
@@ -7,284 +7,458 @@ import { ops } from "./ops";
...
+};
+
+// External or internal receivers
+// Bounced receivers are not included because only internal receivers can be bounced
+type Receivers = {
+    kind: "internal" | "external";
+    empty: ReceiverDescription | undefined;
+    binary: ReceiverDescription[];
+    comment: ReceiverDescription[];
```
Comment (anton-trunov) [inline src/generator/writers/writeRouter.ts:30]:
```suggestion
    readonly binary: readonly ReceiverDescription[];
    readonly comment: readonly ReceiverDescription[];
```

File: src/generator/writers/writeRouter.ts [hunk 4]
```diff
@@ -7,284 +7,458 @@ import { ops } from "./ops";
...
+            `self~${ops.receiveAny(contractName, receivers.kind)}(in_msg);`,
+        );
+        wCtx.append("return (self, true);");
+        return;
+    }
+
+    // If there is a fallback receiver and binary/string receivers, we need to keep in_msg intact,
+    // otherwise we can modify in_msg in-place
+    const opcodeReader: "~load" | ".preload" =
+        typeof receivers.fallback === "undefined" ? "~load" : ".preload";
```
Comment (anton-trunov) [inline src/generator/writers/writeRouter.ts]:
```suggestion
    const opcodeReader: "~load_int" | ".preload_int" =
        typeof receivers.fallback === "undefined" ? "~load_int" : ".preload_int";
```

File: src/generator/writers/writeRouter.ts [hunk 5]
```diff
@@ -7,284 +7,464 @@ import { ops } from "./ops";
...
-                    // Exit
-                    ctx.append("return (self, true);");
-                });
-                ctx.append(`}`);
-            }
+function writeCommentReceivers(
+    commentReceivers: ReceiverDescription[],
+    commentFallbackReceiver: ReceiverDescription | undefined,
+    kind: "internal" | "external",
+    opcodeReader: ".preload_uint" | "~load_uint",
```
Comment (Kaladin13) [inline src/generator/writers/writeRouter.ts]: >  opcodeReader: ".preload_uint" | "~load_uint",

Maybe we should pass this around as boolean/some other representation? For example `doesFallbackReceiverExist` 

In current implementation this parameter doesn't represent its true value

File: src/test/benchmarks/escrow/results.json [hunk 6]
```diff
@@ -30,13 +30,23 @@
...
+      "commit": "https://github.com/tact-lang/tact/pull/1854"
+    },
     {
       "label": "master",
       "gas": {
-        "fundingTon": "6376",
-        "changeCode": "5500",
-        "approveTon": "11164",
-        "cancelTon": "8663"
+        "fundingTon": "6414",
```
Comment (Kaladin13) [inline src/test/benchmarks/escrow/results.json:46]: Based on README and #1556 it seems that we shouldn't loose any gas here, maybe we need to manually check fift code diff before merge to be sure that gas overhead is on the Asm.fif and not on the codegen

File: src/test/benchmarks/escrow/results.json [hunk 7]
```diff
@@ -30,13 +30,23 @@
       },
       "commit": "https://github.com/tact-lang/tact/pull/1800"
     },
+    {
+      "label": "No double checking of message opcodes",
```
Comment (Kaladin13) [inline src/test/benchmarks/escrow/results.json:34]:
```suggestion
      "label": "1.5.3 with no double checking of message opcodes",
```

**Review by Kaladin13 — COMMENTED** [review]
Few notes

**Review by verytactical — DISMISSED** [review]
LGTM

File: src/test/benchmarks/escrow/results.json (hunk 6 above)
Comment (verytactical) [reply src/test/benchmarks/escrow/results.json:46]: Already did, but thanks :)

File: src/test/benchmarks/escrow/results.json (hunk 7 above)
Comment (anton-trunov) [reply src/test/benchmarks/escrow/results.json:34]: I was trying to keep the surrounding style

File: src/generator/writers/writeRouter.ts (hunk 5 above)
Comment (anton-trunov) [reply src/generator/writers/writeRouter.ts]: @Kaladin13 please check out the change

Comment (Kaladin13) [reply src/generator/writers/writeRouter.ts]: Look good, that's exactly what I had in mind

File: src/test/benchmarks/escrow/results.json (hunk 7 above)
Comment (Kaladin13) [reply src/test/benchmarks/escrow/results.json:34]: I guess that's resolved for now and will be revisited at #1865

**Review by Kaladin13 — APPROVED** [review]
Good to go!
