### PR TITLE
fix: throw an error if non-optional method is called on an optional type

### LINKED ISSUE #2766: Forbid calling an extension function for type T on an expression with type T?
Example:
```tact
contract Test {
    addr: Address?;

    receive() {
        if (self.addr.isNotNone()) {
            throw(10);
        }
    }
}

inline extends fun isNotNone(self: Address): Bool { return self.asSlice().preloadUint(2) != 0 }
```

### PR DESCRIPTION
**Pull request by i582**
## Issue

Closes #2766.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases

### CODE REVIEW

File: src/types/resolveExpression.ts [hunk 1]
```diff
@@ -643,6 +643,18 @@ function resolveCall(
                 checkParameterType(exp.args[i]!, a, ctx);
             }
 
+            if (f.self) {
+                const selfIsOptional =
+                    f.self.kind === "ref" ? f.self.optional : false;
+
+                if (src.optional && !selfIsOptional) {
+                    throwCompilationError(
+                        `Cannot call method ${idTextErr(exp.method)} on an expression of type "${src.name}?" (optional ${src.name}) without unwrapping it first. Add "!!" before the method call to unwrap an optional value`,
```
Comment (novusnota) [inline src/types/resolveExpression.ts]:
```suggestion
                        `Cannot call method ${idTextErr(exp.method)} on an expression of type "${src.name}?" (optional ${src.name}) without unwrapping it with "!!" first`,
```

File: src/types/__snapshots__/resolveStatements.spec.ts.snap [hunk 2]
```diff
@@ -81,6 +81,15 @@ exports[`resolveStatements should fail statements for bounced-type-is-smaller 1`
 "
 `;
 
+exports[`resolveStatements should fail statements for call-non-optional-method-on-optional 1`] = `
+"<unknown>:10:13: Cannot call method "isNotNone" on an expression of type "Address?" (optional Address) without unwrapping it first. Add "!!" before the method call to unwrap an optional value
```
Comment (novusnota) [inline src/types/__snapshots__/resolveStatements.spec.ts.snap]:
```suggestion
"<unknown>:10:13: Cannot call method "isNotNone" on an expression of type "Address?" (optional Address) without unwrapping it unwrapping it with "!!" first
```

**Review by novusnota — CHANGES_REQUESTED** [review]
simplified the error message

File: src/types/__snapshots__/resolveStatements.spec.ts.snap (hunk 2 above)
Comment (i582) [reply src/types/__snapshots__/resolveStatements.spec.ts.snap]: Done

File: src/types/resolveExpression.ts (hunk 1 above)
Comment (i582) [reply src/types/resolveExpression.ts]: Done

**Review by anton-trunov — DISMISSED** [review]

**Review by novusnota — DISMISSED** [review]

**Review by anton-trunov — APPROVED** [review]
