### PR TITLE
fix(ts-wrappers): fix TypeScript wrappers generation for messages with single quote

### LINKED ISSUE #972: Invalid string escaping in generated typescript code
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
contract Test{
 receive("test'"){
    self.reply("OK");
 }
}
```

### Relevant Tact/build system log output

_No response_

### What happened?

Tact compiler generated incorrect typescript code:
```typescript
    async send(provider: ContractProvider, via: Sender, args: { value: bigint, bounce?: boolean| null | undefined }, message: 'cancel'') {
     //blablabla     
    }


```

### What did you expect?

I expected, that the generated typescript strings would contain escaped contents

### Steps to reproduce

_No response_

### How do you run Tact?

Blueprint

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by i582**
Hey, this particular bug is not that important, of course, but it's still a great option to dig into the project :)

I haven't found any test cases for TS wrappers. Does Tact plan to create (or have) one?

Fixes #972

### CODE REVIEW

**Comment by novusnota** [comment]
> Hey, this particular bug is not that important, of course, but it's still a great option to dig into the project :)

Thank you kindly for the contribution!

> I haven't found any test cases for TS wrappers. Does Tact plan to create (or have) one?

That would be nice, but there are no immediate plans (ok, now there are: #1107). We have a [good-to-have plans](https://github.com/tact-lang/tact/issues/255) to make the wrapper generation system a bit more flexible to allow making wrappers for multiple languages, but those are a bit far-fetched now that the team is focusing more efforts on many other areas of the compiler.

@i582 Could you please add an entry to the CHANGELOG.md?

**Comment by i582** [comment]
@novusnota done

**Review by novusnota — DISMISSED** [review]
LGTM, but let's wait for the input from @verytactical, @anton-trunov and others :)

File: src/bindings/writeTypescript.ts [hunk 1]
```diff
@@ -352,7 +352,12 @@ export function writeTypescript(
                                 r.message.text !== null &&
                                 r.message.text !== undefined
                             ) {
-                                receivers.push(`'${r.message.text}'`);
+                                // since we are using single quotes, escape them in the message name
+                                const escaped = r.message.text.replace(
```
Comment (verytactical) [inline src/bindings/writeTypescript.ts]: Could there also be a `\` in `r.message.text`?

Probably `JSON.stringify(r.message.text)` is what we need here.

Comment (i582) [reply src/bindings/writeTypescript.ts]: AFAIK, `JSON.stringify` doesn't escape `'` in string 🤔

Comment (novusnota) [reply src/bindings/writeTypescript.ts]: > Could there also be a \ in r.message.text?

Only a double one, like `\\`, https://github.com/tact-lang/tact/blob/229ce26cf95023ceff3d754d2622501d70b83cb6/src/grammar/grammar.ohm#L340

Comment (i582) [reply src/bindings/writeTypescript.ts]: also:
```
TactParseError: test/main.tact:15:17: Parse error: expected "\""

Line 15, col 17:
  14 | 
> 15 |     receive("get\'") {
                       ^
  16 | 
```

Comment (i582) [reply src/bindings/writeTypescript.ts]: But maybe we can just use:
```js
`string`
```

Comment (verytactical) [reply src/bindings/writeTypescript.ts]: > doesn't escape ' in string

That wouldn't be a problem if it was a `"`-string, would it? :D

> Only a double one, like `\\`

Then it probably shouldn't matter. It's just that serializing JS-compatible string is easily done with `JSON.stringify`, and there isn't really any way it can go wrong (JS-syntax-wise). If the goal is to generate TS in a way that when it runs runtime has the same exact string, `stringify` is the best option.

Comment (i582) [reply src/bindings/writeTypescript.ts]: > That wouldn't be a problem if it was a `"`-string, would it? :D

Yeah, but then it's better to use '`' and escape only it in the string (less problems with any \\ things)

Comment (i582) [reply src/bindings/writeTypescript.ts]: > Then it probably shouldn't matter. It's just that serializing JS-compatible string is easily done with `JSON.stringify`, and there isn't really any way it can go wrong (JS-syntax-wise). If the goal is to generate TS in a way that when it runs runtime has the same exact string, `stringify` is the best option.

Now I understand, this seems like the best solution of all

**Comment by anton-trunov** [comment]
@i582 Hi, thanks for the contribution. The original PR template had some pointers on our PR merging policy and it requires adding tests to make sure this bug won't creep in later after some refactoring, for instance.

**Comment by i582** [comment]
> it requires adding tests to make sure this bug won't creep in later after some refactoring, for instance.

Yeah, I saw that, that's why I asked about tests. However, since there are no tests for wrappers yet (as I understand), what tests could I add, @anton-trunov?

**Comment by anton-trunov** [comment]
@i582 you can use the example from the linked issue, e.g. by including an apostrophe into one of the string receiver's in the end-to-end tests (see `e2e-emulated` folder)

**Comment by i582** [comment]
Thank you, @anton-trunov! I added test for different messages

**Review by verytactical — APPROVED** [review]
LGTM

**Comment by anton-trunov** [comment]
@i582 Thanks a bunch!
