### PR TITLE
fix: check new variable bindings do not shadow global constants

### LINKED ISSUE #676: Constant shadowing does not produce var-scope error
```
const foo: Int = 42;

contract Test {
    get fun bar(): Int {
        let foo = 43;  // <--- attempt to shadow `foo` constant
        return foo;
    }
}
```

Moreover, the constant substitution algorithm does not respect scoping rules and the `bar` getter returns `42` instead of expected `43`.

### PR DESCRIPTION
**Pull request by anton-trunov**
Closes #676

- [x] I have updated CHANGELOG.md
- ~[ ] I have documented my contribution in Tact Docs: https://github.com/tact-lang/tact-docs/pull/PR-NUMBER~
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Comment by anton-trunov** [comment]
Please let me know if there are any issues in this PR and I'll happily fix those in a follow-up, but now I'm going to merge this one to fix the other issues for v1.4.2

File: src/types/resolveStatements.ts [hunk 1]
```diff
@@ -81,15 +92,16 @@ function removeRequiredVariable(
 function addVariable(
     name: AstId,
     ref: TypeRef,
-    src: StatementContext,
+    ctx: CompilerContext,
+    sctx: StatementContext,
 ): StatementContext {
-    checkVariableExists(src, name); // Should happen earlier
+    checkVariableExists(ctx, sctx, name); // Should happen earlier
     if (isWildcard(name)) {
```
Comment (jeshecdom) [inline src/types/resolveStatements.ts:99]: Ohhh, interesting. I did not check in the interpreter the use of wildcard identifiers (to be honest, I was not aware of them). Where is the wildcard _ allowed in Tact? Anywhere where an identifier is allowed? I looked in the grammar and it seems that _ is allowed by the id rule. _ allows you to ignore that identifier, right? I am asking this for the interpreter :)

File: src/types/resolveStatements.ts [hunk 2]
```diff
@@ -197,7 +209,7 @@ function processStatements(
                     ctx = resolveExpression(s.expression, sctx, ctx);
 
                     // Check variable name
-                    checkVariableExists(sctx, s.name);
+                    checkVariableExists(ctx, sctx, s.name);
```
Comment (jeshecdom) [inline src/types/resolveStatements.ts:212]: Is there any reason as to why call `checkVariableExists` at this point if later `addVariable` will call it in both branches of the conditional? I guess to give the user the variable duplication and shadowing errors as soon as possible.

File: src/types/resolveStatements.ts [hunk 3]
```diff
@@ -486,11 +498,12 @@ function processStatements(
                     let catchCtx = sctx;
 
                     // Process catchName variable for exit code
-                    checkVariableExists(initialCtx, s.catchName);
+                    checkVariableExists(ctx, initialSctx, s.catchName);
```
Comment (jeshecdom) [inline src/types/resolveStatements.ts:501]: Again. Why call `checkVariableExists` if `addVariable` is the first thing that it does in the next line?

File: src/types/resolveStatements.ts (hunk 1 above)
Comment (anton-trunov) [reply src/types/resolveStatements.ts:99]: Right, underscores (`_`) means an identifier that cannot be used (so the shadowing rules do not apply to them). You can use it as a function parameter, in `catch`-blocks, `foreach`-loops, unused `let`-bindings.

File: src/types/resolveStatements.ts (hunk 2 above)
Comment (anton-trunov) [reply src/types/resolveStatements.ts:212]: I actually didn't think about this, I just added `ctx` mechanically here.

File: src/types/resolveStatements.ts (hunk 3 above)
Comment (anton-trunov) [reply src/types/resolveStatements.ts:501]: We could try refactor this, although I'm not sure how useful this is going to be since we are going to replace the existing typechecker with a new one

Comment (jeshecdom) [reply src/types/resolveStatements.ts:501]: Agreed. I think there is no need to refactor.
