### PR TITLE
Enhance error handling to support third-party tools

### LINKED ISSUE #262: Enhance error handling in Tact compiler to support third-party tools
Currently, the Tact compiler logs all errors directly to the console. For integration with third-party tools like [Nujan Web IDE](https://ide.nujan.io/), it's necessary to modify the error handling behavior to throw these errors, rather than just logging them.

**Expected Behavior:**
Errors should be thrown programmatically, allowing third-party tools to catch and process these errors accordingly.

**Additional Context:**
This enhancement is crucial for improving the interoperability of the Tact compiler with various third-party development tools, which rely on catching exceptions to handle errors more effectively.

### PR DESCRIPTION
**Pull request by rahulyadav-57**
Closes #262 

- [x] I have updated CHANGELOG.md
- ~[ ] I have documented my contribution in Tact Docs: https://github.com/tact-lang/tact-docs/pull/PR-NUMBER~
- ~[ ] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases~
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: scripts/prepare.ts [hunk 1]
```diff
@@ -64,15 +66,15 @@ import { __DANGER__disableVersionNumber } from "../src/pipeline/version";
                             content: code,
                         },
                     ],
-                    logger: consoleLogger,
+                    logger: logger,
                 });
                 if (!c.ok) {
-                    console.error(c.log);
+                    logger.error(c.log);
                     process.exit(1);
```
Comment (anton-trunov) [inline scripts/prepare.ts]: My guess would be that all things like `process.exit` should also go

**Comment by anton-trunov** [comment]
Any progress here?

File: src/logger.ts [hunk 2]
```diff
@@ -1,9 +1,87 @@
...
+
+    protected log(level: LogLevel, message: messageType) {
+        if (this.level === LogLevel.NONE) {
+            return;
+        }
+
+        if (message instanceof Error) {
+            message = message.stack || message.message;
+        } else {
+            message = "" + message.toString();
```
Comment (byakuren-hijiri) [inline src/logger.ts]: Can we simply use `message.toString()` here?

File: src/pipeline/build.ts [hunk 3]
```diff
@@ -326,16 +336,18 @@ export async function build(args: {
                 bindingsServer,
             );
         } catch (e) {
-            logger.error("Bindings compiler crashed");
-            logger.error(errorToString(e));
-            return false;
+            const message = "Bindings compiler crashed";
+            logger.error(message);
+            logger.error(e as Error);
+            errorMessages.push(new Error(message));
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]: Should we also include `e` to the `errorMessages` structure? It might be useful to third-parties, I think.

File: src/pipeline/build.ts [hunk 4]
```diff
@@ -344,11 +356,13 @@ export async function build(args: {
             );
             project.writeFile(pathBindings, report);
         } catch (e) {
-            logger.error("Report generation crashed");
-            logger.error(errorToString(e));
-            return false;
+            const message = "Report generation crashed";
+            logger.error(message);
+            logger.error(e as Error);
+            errorMessages.push(new Error(message));
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]: See previous

File: src/node.ts [hunk 5]
```diff
@@ -64,33 +65,42 @@ export async function run(args: {
     configPath?: string;
     projectNames?: string[];
     additionalCliOptions?: AdditionalCliOptions;
+    suppressLog?: boolean;
 }) {
     const configWithRootPath = await loadConfig(args.fileName, args.configPath);
     if (!configWithRootPath) {
-        return false;
+        return { ok: false, error: [new Error("Unable to load config")] };
```
Comment (byakuren-hijiri) [inline src/node.ts]: nit: Maybe we should add `args.configPath` to the error message in order to give more context to the user.

File: src/pipeline/build.ts [hunk 6]
```diff
@@ -8,32 +8,32 @@ import { funcCompile } from "../func/funcCompile";
...
 import { idText } from "../grammar/ast";
+import { TactErrorCollection } from "../errors";
 
 export async function build(args: {
     config: ConfigProject;
     project: VirtualFileSystem;
     stdlib: string | VirtualFileSystem;
-    logger?: TactLogger | null | undefined;
-}) {
+    logger?: Logger | null | undefined;
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]: This type definition looks a bit strange, right? What is the different between `null` and `undefined` values? What value will be used if we write `if (!logger) {` in the function body?

File: src/pipeline/build.ts [hunk 7]
```diff
@@ -111,7 +112,7 @@ export async function build(args: {
         let codeEntrypoint: string;
 
         // Compiling contract to func
-        logger.log("   > " + contract + ": tact compiler");
+        logger.info("   > " + contract + ": tact compiler");
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]: nit: Maybe we should use string interpolation in the similar cases instead. AFAIK we prefer that style when refactoring the project, but it's up to you.

File: src/pipeline/build.ts (hunk 3 above)
Comment (rahulyadav-57) [reply src/pipeline/build.ts]: Yes, that would be a better.

File: src/pipeline/build.ts (hunk 6 above)
Comment (rahulyadav-57) [reply src/pipeline/build.ts]: I think we can remove both `null` and `undefined` since it will be `undefined` by default.

File: src/node.ts (hunk 5 above)
Comment (rahulyadav-57) [reply src/node.ts]: We can change it to something \`Unable to load config from path: ${args.configPath}\`

File: src/pipeline/build.ts (hunk 7 above)
Comment (rahulyadav-57) [reply src/pipeline/build.ts]: Yes, I'll do it. I haven't done the refactoring yet, but I'll take care of it.

**Review by anton-trunov — DISMISSED** [review]
LGTM, but let's wait for @byakuren-hijiri to approve

File: bin/tact [hunk 8]
```diff
@@ -165,9 +165,9 @@ meowModule.then(
         projectNames: cli.flags.projects ?? [],
         additionalCliOptions: { mode },
       })
-      .then((success) => {
+      .then((response) => {
```
Comment (novusnota) [inline bin/tact:168]: Two points here:
1. It would be nice to add a `--quiet` flag, which would be passed to `suppressLog: ...` argument of `run()`
2. If there's no `--quiet` flag, it would be nice to peek into `response.error` and display them onto console before we do `process.exit(...)`

Other than that, splendid work!

Comment (anton-trunov) [reply bin/tact:168]: @novusnota can you please help with this flag since you already have experience with meow? just push your commit to this PR

Comment (novusnota) [reply bin/tact:168]: Sure!

Comment (novusnota) [reply bin/tact:168]: Hmm, seems like adding `response.error` doubles the error output:

```ts
// bin/tact
// ...
main
  .run({
    fileName: cli.input.at(0),
    configPath: cli.flags.config,
    projectNames: cli.flags.projects ?? [],
    additionalCliOptions: { mode },
    suppressLog: cli.flags.quiet
  })
  .then((response) => {
    // Log errors if --quiet is not set
    if (!cli.flags.quiet) {
      response.error.map(err => console.log(err)); // ← this logs errors AFTER the main log output with them showed already, which isn't nice
    }
    // https://nodejs.org/docs/v20.12.1/api/process.html#exit-codes
    process.exit(response.ok ? 0 : 30);
  });
```

Not a big deal though, can omit the `reponse.error.map...`

File: scripts/prepare.ts [hunk 9]
```diff
@@ -15,74 +15,84 @@ import { __DANGER__disableVersionNumber } from "../src/pipeline/version";
...
-        ),
-    )) {
-        const res = await verify({ pkg: fs.readFileSync(pkgPath, "utf-8") });
-        if (!res.ok) {
-            console.error("Failed to verify " + pkgPath + ": " + res.error);
-            process.exit(1);
+    try {
+        // Compile projects
+        const compileResult = await run({
+            configPath: path.join(__dirname, "../tact.config.json"),
```
Comment (byakuren-hijiri) [inline scripts/prepare.ts]:
```suggestion
            configPath: path.join(__dirname, "..", "tact.config.json"),
```

File: scripts/prepare.ts [hunk 10]
```diff
@@ -15,74 +15,84 @@ import { __DANGER__disableVersionNumber } from "../src/pipeline/version";
...
-                            content: code,
-                        },
-                    ],
-                    logger: logger,
-                });
-                if (!c.ok) {
-                    logger.error(c.log);
-                    process.exit(1);
+        // Compile func files
+        for (const p of [{ path: path.join(__dirname, "/../func/") }]) {
```
Comment (byakuren-hijiri) [inline scripts/prepare.ts]:
```suggestion
        for (const p of [{ path: path.join(__dirname, "..", "func") }]) {
```

File: scripts/prepare.ts [hunk 11]
```diff
@@ -15,74 +15,84 @@ import { __DANGER__disableVersionNumber } from "../src/pipeline/version";
...
-                process.exit(1);
-            }
-            fs.writeFileSync(p.path + r + ".fift", c.fift!);
-            fs.writeFileSync(p.path + r + ".cell", c.output!);
 
-            // Cell -> Fift decompiler
-            const source = decompileAll({ src: c.output! });
-            fs.writeFileSync(p.path + r + ".rev.fift", source);
+                // Precompile
+                logger.info(`Processing ${path.join(p.path + r)}`);
```
Comment (byakuren-hijiri) [inline scripts/prepare.ts]: nit: I would create a local variable `p.path+r` and reuse it here and below. It could save us from regression errors when refactoring this path later. But it's up to you.

File: src/pipeline/build.ts [hunk 12]
```diff
@@ -336,10 +336,10 @@ export async function build(args: {
                 bindingsServer,
             );
         } catch (e) {
-            const message = "Bindings compiler crashed";
-            logger.error(message);
-            logger.error(e as Error);
-            errorMessages.push(new Error(message));
+            const error = e as Error;
+            error.message = `Bindings compiler crashed, ${error.message}`;
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
            error.message = `Bindings compiler crashed: ${error.message}`;
```

File: src/pipeline/build.ts [hunk 13]
```diff
@@ -356,10 +356,10 @@ export async function build(args: {
             );
             project.writeFile(pathBindings, report);
         } catch (e) {
-            const message = "Report generation crashed";
-            logger.error(message);
-            logger.error(e as Error);
-            errorMessages.push(new Error(message));
+            const error = e as Error;
+            error.message = `Report generation crashed, ${error.message}`;
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
            error.message = `Report generation crashed: ${error.message}`;
```

File: src/node.ts [hunk 14]
```diff
@@ -98,7 +115,7 @@ export async function run(args: {
         false,
     ); // Improves developer experience
     for (const config of projects) {
-        consoleLogger.log("💼 Compiling project " + config.name + "...");
+        logger.info("💼 Compiling project " + config.name + "...");
```
Comment (byakuren-hijiri) [inline src/node.ts]:
```suggestion
        logger.info(`💼 Compiling project ${config.name} ...`);
```

File: src/pipeline/build.ts [hunk 15]
```diff
@@ -141,7 +143,7 @@ export async function build(args: {
         }
 
         // Compiling contract to TVM
-        logger.log("   > " + contract + ": func compiler");
+        logger.info("   > " + contract + ": func compiler");
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
        logger.info(`   > ${contract}: func compiler`);
```

File: src/pipeline/build.ts [hunk 16]
```diff
@@ -192,39 +196,42 @@ export async function build(args: {
 
         if (config.mode === "fullWithDecompilation") {
             // Fift decompiler for generated code debug
-            logger.log("   > " + contract + ": fift decompiler");
+            logger.info("   > " + contract + ": fift decompiler");
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
            logger.info(`   > ${contract}: fift decompiler`);
```

File: src/pipeline/build.ts [hunk 17]
```diff
@@ -192,39 +196,42 @@ export async function build(args: {
...
     const contracts = getContracts(ctx);
     const packages: PackageFileFormat[] = [];
     for (const contract of contracts) {
-        logger.log("   > " + contract);
+        logger.info("   > " + contract);
         const artifacts = built[contract];
         if (!artifacts) {
-            logger.error("   > " + contract + ": no artifacts found");
-            return false;
+            const message = "   > " + contract + ": no artifacts found";
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
            const message = `   > ${contract}: no artifacts found`;
```

File: src/pipeline/build.ts [hunk 18]
```diff
@@ -298,17 +307,18 @@ export async function build(args: {
     }
 
     // Bindings
-    logger.log("   > Bindings");
+    logger.info("   > Bindings");
     for (const pkg of packages) {
-        logger.log("   > " + pkg.name);
+        logger.info("   > " + pkg.name);
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]:
```suggestion
        logger.info(`   > ${pkg.name}`);
```

File: src/pipeline/build.ts [hunk 19]
```diff
@@ -298,17 +307,18 @@ export async function build(args: {
...
         if (pkg.init.deployment.kind !== "system-cell") {
-            logger.error(
+            const message =
                 "   > " +
-                    pkg.name +
-                    ": unsupported deployment kind " +
-                    pkg.init.deployment.kind,
-            );
-            return false;
+                pkg.name +
```
Comment (byakuren-hijiri) [inline src/pipeline/build.ts]: Let's use string interpolation here

**Review by byakuren-hijiri — DISMISSED** [review]
Let's refactor existing sources a little bit and fix the operations with paths to avoid cross-platform problems. After that, LGTM.

**Comment by anton-trunov** [comment]
I just pushed two fixes, let's see if the tests are green and merge it

**Review by anton-trunov — APPROVED** [review]
