### PR TITLE
fix: handle `coins` for map key and value types correctly

### LINKED ISSUE #767: Internal compiler error when parsing a map from slice
### Are you using the latest released (or pre-released, a.k.a. "next") version?

- [X] I'm using the latest Tact version

### Tact source code

```tact
message(42) Foo {
    s: Slice as remaining;
}

struct Dict {
    m: map<Int as uint8, Int as coins>;
}

contract Test {
    receive(msg: Foo) {
        let d = Dict.fromSlice(msg.s);
    }
}
```

### Relevant Tact/build system log output

```shell
❯ tact test.tact
💼 Compiling project test ...
   > Test: tact compiler
   > Test: func compiler
   > Packaging
   > Test
   > Bindings
   > Test
Error: Bindings compiler crashed: [INTERNAL COMPILER ERROR]: Unsupported type: {"kind":"dict","key":"uint","keyFormat":8,"value":"uint","valueFormat":"coins"}
Please report at https://github.com/tact-lang/tact/issues
    at throwInternalCompilerError (/Users/anton_1/ton/tact/dist/errors.js:83:11)
    at throwUnsupportedType (/Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:8:45)
    at /Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:22:13
    at Writer.inIndent (/Users/anton_1/ton/tact/dist/utils/Writer.js:10:9)
    at writeStruct (/Users/anton_1/ton/tact/dist/bindings/typescript/writeStruct.js:12:7)
    at writeTypescript (/Users/anton_1/ton/tact/dist/bindings/writeTypescript.js:117:43)
    at build (/Users/anton_1/ton/tact/dist/pipeline/build.js:275:74)
    at async Object.run (/Users/anton_1/ton/tact/dist/node.js:100:23)
```

### What happened?

See the error message above.

### What did you expect?

It should compile and produce TS bindings

### Steps to reproduce

_No response_

### How do you run Tact?

Tact CLI

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Gusarich**
## Issue

Closes #767.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/bindings/typescript/serializers.ts [hunk 1]
```diff
@@ -738,6 +738,8 @@ const map: Serializer<MapSerializerDescr> = {
                     src.valueFormat === undefined
                 ) {
                     value = { kind: "uint", bits: 256 };
+                } else if (src.valueFormat === "coins") {
+                    value = { kind: "uint", bits: 124 };
```
Comment (novusnota) [inline src/bindings/typescript/serializers.ts:742]: Shouldn't this be changed in the `src/storage/allocator.ts` too?

Comment (anton-trunov) [reply src/bindings/typescript/serializers.ts:742]: @novusnota Which place exactly do you mean?

File: src/types/resolveSignatures.ts [hunk 2]
```diff
@@ -140,6 +140,11 @@ export function resolveSignatures(ctx: CompilerContext) {
                         `Unsupported map format: ${src.type.format}`,
                     );
                 }
+                if (src.type.keyFormat === "coins") {
+                    throwCompilationError(
+                        `Unsupported format ${src.type.keyFormat} for map key`,
```
Comment (anton-trunov) [inline src/types/resolveSignatures.ts:145]: Hmmm, why cannot we support the `coins` storage annotation for map key types?

Comment (anton-trunov) [reply src/types/resolveSignatures.ts:145]: AFAIR, there is support in TVM for variable size keys in hashmaps

Comment (Gusarich) [reply src/types/resolveSignatures.ts:145]: There are no TVM instructions for VarHashmap at the moment

Comment (anton-trunov) [reply src/types/resolveSignatures.ts:145]: Ah, then perhaps `tvm.pdf` was a bit too optimistic :)

**Review by anton-trunov — APPROVED** [review]

File: src/bindings/typescript/serializers.ts (hunk 1 above)
Comment (novusnota) [reply src/bindings/typescript/serializers.ts:742]: Oh, nevermind, realised that's redundant :)
