### PR TITLE
fix: better error messages for empty `bounced()` and `bounced("string")`

### LINKED ISSUE #1984: Improve error message on `bounced()`
In this contract:
```
contract Test {

    bounced() {
     
    }
}
```
the compiler reports the error:
```
bounced() cannot be used as fallback
  2 | 
> 3 |     bounced() {
          ^~~~~~~~~~~
```
which made me believe that by adding the bounced fallback on slices:
```
contract Test {

    bounced() {
     
    }
    
    bounced(msg: Slice) {
     
    }
}
```
the error would go away, but it keeps saying the same error. My reasoning was as follows: "If the error message is telling me that I cannot use `bounced()` as a fallback, then adding the actual fallback `bounced(slice)` would allow me to use `bounced()`".

A clearer error message would simply say "`bounced()` is not allowed as a bounced receiver". Or even simply say the more informative error message when one adds `bounced(String)`:

"Bounce receive function can only accept bounced message, message or Slice"

### PR DESCRIPTION
**Pull request by i582**
## Issue

Closes #1984.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/grammar/parser-error.ts [hunk 1]
```diff
@@ -74,11 +74,13 @@ export const syntaxErrorSchema = <T, U>(
             return handle(sub`Expression is not callable`);
         },
         noBouncedWithoutArg: () => {
-            return handle(sub`bounced() cannot be used as fallback`);
+            return handle(
+                sub`bounced() receiver should accept one of Message, bounced<Message> or Slice`,
```
Comment (novusnota) [inline src/grammar/parser-error.ts]:
```suggestion
                sub`bounced() receiver accepts a Message, bounced<Message> or Slice`,
```

Not sure if it's better, but it's more concise

File: src/grammar/parser-error.ts [hunk 2]
```diff
@@ -74,11 +74,13 @@ export const syntaxErrorSchema = <T, U>(
...
+            );
         },
         noBouncedWithString: () => {
             return handle(
-                sub`bounced() cannot be used with a string literal name`,
+                sub`bounced() receiver can only accept Message, bounced<Message> or Slice`,
```
Comment (novusnota) [inline src/grammar/parser-error.ts]:
```suggestion
                sub`bounced() receiver accepts a Message, bounced<Message> or Slice`,
```

Comment (i582) [reply src/grammar/parser-error.ts]: Fixed

File: src/grammar/parser-error.ts (hunk 1 above)
Comment (i582) [reply src/grammar/parser-error.ts]: Fixed

**Review by anton-trunov — CHANGES_REQUESTED** [review]
Let's fix it for the old parser as well

**Review by novusnota — APPROVED** [review]
