### PR TITLE
fix: don't show internal error for unknown types for variables

### LINKED ISSUE #2003: Internal compiler error for unknown type in variable type hint
```
let targetJettonWallet: Address2 =
//                      ^^^^^^^^ unknown type
    (workchain == Workchain) ?
    contractMasterchainAddress(initOf JettonWallet(msg.ownerAddress, myAddress()))
    : emptyMasterchainAddress();
```

```
Error: [INTERNAL COMPILER ERROR]: Type Address2 not found
Please report at https://github.com/tact-lang/tact/issues
    at throwInternalCompilerError (/Users/petrmakhnev/tact/src/error/errors.ts:98:11)
    at getType (/Users/petrmakhnev/tact/src/types/resolveDescriptors.ts:2102:35)
    at resolveTypeRef (/Users/petrmakhnev/tact/src/types/resolveDescriptors.ts:139:23)
    at processStatements (/Users/petrmakhnev/tact/src/types/resolveStatements.ts:253:60)
    at processFunctionBody (/Users/petrmakhnev/tact/src/types/resolveStatements.ts:765:17)
    at resolveStatements (/Users/petrmakhnev/tact/src/types/resolveStatements.ts:927:19)
    at precompile (/Users/petrmakhnev/tact/src/pipeline/precompile.ts:37:28)
    at build (/Users/petrmakhnev/tact/src/pipeline/build.ts:100:25)
    at run (/Users/petrmakhnev/tact/src/cli/tact/index.ts:305:34)
    at async allInFolder (/Users/petrmakhnev/tact/src/test/utils/all-in-folder.build.ts:39:31)
```

### PR DESCRIPTION
**Pull request by i582**
## Issue

Closes #2003.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

**Review by novusnota — DISMISSED** [review]
```
 ______
( LGTM )
 ¯¯¯¯¯¯
    o
     o
                                   .::!!!!!!!:.
  .!!!!!:.                        .:!!!!!!!!!!!!
  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$ 
      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P 
      $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$# 
      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$* 
      ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R" 
        "*$bd$$$$      '*$$$$$$$$$$$o+#" 
             """"          """""""
```

File: src/types/resolveDescriptors.ts [hunk 1]
```diff
@@ -2095,11 +2104,15 @@ export function resolveDescriptors(ctx: CompilerContext, Ast: FactoryAst) {
 export function getType(
     ctx: CompilerContext,
     ident: A.AstId | A.AstTypeId | string,
+    loc?: SrcInfo,
```
Comment (anton-trunov) [inline src/types/resolveDescriptors.ts]: `AstId` and `AstTypeId` already have locations let's check that (and call `getType` without `idText` where possible)

Comment (i582) [reply src/types/resolveDescriptors.ts]: Good point, we now use their location and fallback to the `loc` parameter for strings (new places where I added `loc` argument call `getType` with the string)

File: src/types/resolveDescriptors.ts [hunk 2]
```diff
@@ -136,7 +137,7 @@ export const toBounced = (type: string) => `${type}%%BOUNCED%%`;
 export function resolveTypeRef(ctx: CompilerContext, type: A.AstType): TypeRef {
     switch (type.kind) {
         case "type_id": {
-            const t = getType(ctx, idText(type));
+            const t = getType(ctx, idText(type), type.loc);
```
Comment (anton-trunov) [inline src/types/resolveDescriptors.ts]:
```suggestion
            const t = getType(ctx, type);
```

and in similar places

File: src/types/resolveDescriptors.ts (hunk 1 above)
Comment (anton-trunov) [reply src/types/resolveDescriptors.ts]: I think you don't actually need `loc?`

File: src/types/resolveDescriptors.ts (hunk 2 above)
Comment (i582) [reply src/types/resolveDescriptors.ts]: oh, indeed, fixed

File: src/types/resolveDescriptors.ts (hunk 1 above)
Comment (i582) [reply src/types/resolveDescriptors.ts]: Removed

**Review by anton-trunov — APPROVED** [review]
