### PR TITLE
fix: union with parsedModules

### LINKED ISSUE #2310: Compiling ASTs with references to stdlib causes errors during `resolveDescriptors`
The error is caused by the second step in `precompile`, at the first line of the `openContext` function. When passing the AST through the `parsedModules` optional argument in `openContext`, the `openContext` function drops the `sources` computed in the first step of `precompile` (which contain the `stdlib` declarations): 

```
const modules = parsedModules ?? parseModules(sources, parser);
```
This causes missing reference errors in `resolveDescriptors` later.

It seems to me that instead of dropping `sources`, the function `openContext` should take the union of `sources` plus the optional argument `parsedModules`. Like this:
```
const parsedSources = parseModules(sources, parser);
const modules = typeof parsedModules === "undefined" ? parsedSources : [...parsedSources, ...parsedModules];
```

### LINKED ISSUE #2429: Autogenerate `makeX` functions from AST types
Use the `babel` tool to autogenerate the `makeX` functions. Focus on all the cases for `AstExpression` and `AstStatement` which are the most common used cases in fuzzers.

Place the generated `makeX` functions in a new utility factory, because the current `AstUtil` is used in other places in the code base. Eventually we will need to move the code base into using the new utility factory and delete `AstUtil`.

Add another `yarn` command that runs the script and creates the `.ts` file with all the `makeX` functions.

Related to #1460 and #1327.

### PR DESCRIPTION
**Pull request by jeshecdom**
## Issue

Closes #2310.
Closes #2429.

To run autogeneration of `makeX` functions, execute:
`yarn gen:make-funs`
It will create the file `src/ast/generated/make-factory.ts`.

## Checklist

- [ ] I have updated CHANGELOG.md
- [X] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases

### CODE REVIEW

File: src/context/store.ts [hunk 1]
```diff
@@ -63,7 +65,11 @@ export function openContext(
     parser: Parser,
     parsedModules?: A.AstModule[],
 ): CompilerContext {
-    const modules = parsedModules ?? parseModules(sources, parser);
+    const parsedSources = parseModules(sources, parser);
```
Comment (verytactical) [inline src/context/store.ts]: I would rather make `parsedModules` required, and pass `parseModules(sources, parser)` in regular build.

File: src/test/pipeline/precompile-ast.spec.ts [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+    //
+    // contract Test {
+    //    f: StateInit;
+    //
+    //    init() {
+    //        self.f = initOf Test();
+    //    }
+    // }
+
+    function makeModule(): A.AstModule {
```
Comment (verytactical) [inline src/test/pipeline/precompile-ast.spec.ts]: It seems like this should be a set of definitions in `src/ast/no-src-factory.ts` or even a reuse of existing code for this.

It will be extremely tedious to update manually in case AST definitions change. This code should eventually be generated from AST types.

**Review by verytactical — CHANGES_REQUESTED** [review]
^

File: src/test/pipeline/precompile-ast.spec.ts (hunk 2 above)
Comment (jeshecdom) [reply src/test/pipeline/precompile-ast.spec.ts]: Agreed. I will migrate all the `makeX` functions into that new factory, because this will be a common problem in all PRs involving testing: each one of them defines their own `makeX` functions.

Is there an example on how to generate code for the `makeX` functions just from the AST types? Do you mean like a pre-compilation step, similar to `yarn gen` so that all `makeX` functions are generated?

Comment (jeshecdom) [reply src/test/pipeline/precompile-ast.spec.ts]: Actually, there was a `AstUtil` factory. I think I'll place the `makeX` functions there.

File: src/context/store.ts (hunk 1 above)
Comment (jeshecdom) [reply src/context/store.ts]: The suggested change caused fixes in several `spec` files.

File: src/test/pipeline/precompile-ast.spec.ts (hunk 2 above)
Comment (jeshecdom) [reply src/test/pipeline/precompile-ast.spec.ts]: I added autogeneration of all makeX functions. Please have a look.

Comment (verytactical) [reply src/test/pipeline/precompile-ast.spec.ts]: Thanks!

File: package.json [hunk 3]
```diff
@@ -56,6 +56,7 @@
     "all": "yarn clean && yarn gen && yarn build && yarn coverage && yarn lint:all",
     "next-version": "ts-node version.build.ts",
     "random-ast": "ts-node ./src/ast/random-ast.ts",
+    "gen-make-functions": "ts-node ./src/ast/generated/gen-make-functions-script.ts && yarn prettier -w ./src/ast/generated/make-factory.ts",
```
Comment (verytactical) [inline package.json]: I suggest calling this in line with other scripts, `gen:ast` or something like that.

File: src/ast/generated/gen-make-functions-script.ts [hunk 4]
```diff
@@ -0,0 +1,301 @@
...
+    const createNodeArgsForMake = generalParams.map(({ id, type: _ }) =>
+        t.objectProperty(id, t.identifier(`p_${id.name}`)),
+    );
+    const createNodeArgsForMakeDummy = generalParams.map(({ id, type: _ }) =>
+        id.name === "loc"
+            ? t.objectProperty(id, t.identifier(emptySrcInfo))
+            : t.objectProperty(id, t.identifier(`p_${id.name}`)),
+    );
+    const funReturnType = t.tsTypeReference(
+        t.tSQualifiedName(t.identifier(astNamespace), id),
```
Comment (verytactical) [inline src/ast/generated/gen-make-functions-script.ts]: tSQualifiedName -> tsQualifiedType

File: src/ast/generated/gen-make-functions-script.ts [hunk 5]
```diff
@@ -0,0 +1,301 @@
...
+    }[] = [];
+
+    // If there is no loc field,
+    // the makeDummy function cannot be created
+    const makeDummy = rawFieldsArray.some(
+        (f) => f.key.type === "Identifier" && f.key.name === "loc",
+    );
+
+    for (const field of rawFieldsArray) {
+        if (field.key.type !== "Identifier") {
```
Comment (verytactical) [inline src/ast/generated/gen-make-functions-script.ts]: nit: there is `t.isIdentifier` that returns a guard type, and might be more convenient

File: src/ast/generated/gen-make-functions-script.ts [hunk 6]
```diff
@@ -0,0 +1,301 @@
...
+        .filter((stmt) => stmt?.type === "TSTypeAliasDeclaration");
+
+    const declNames = new Set(decls.map((decl) => decl.id.name));
+
+    const finalFunctions: { name: string; code: string }[] = [];
+
+    // Extract from the declarations all the union types
+    const unionTypes = decls
+        .map((decl) => decl.typeAnnotation)
+        .filter((decl) => decl.type === "TSUnionType");
```
Comment (verytactical) [inline src/ast/generated/gen-make-functions-script.ts]: Guard type likely doesn't help us understand it's a union type in the body of the `for` loop below.

For most means and purposes, `.filter` is worse than just a simple `if ()` for this reason.

File: src/ast/generated/gen-make-functions-script.ts [hunk 7]
```diff
@@ -0,0 +1,301 @@
...
+            } else {
+                // Currently unsupported
+                throw new Error(
+                    "TSNamedTupleMember is currently not supported in TSTupleType",
+                );
+            }
+        }
+
+        default:
+            return typ;
```
Comment (verytactical) [inline src/ast/generated/gen-make-functions-script.ts:302]: I would rather throw an exception here, because there might be (or will be) types with identifiers inside that are not (will not be) handled.

Throwing an exception here would be slightly safer.

File: src/generator/writers/writeExpression.spec.ts [hunk 8]
```diff
@@ -71,11 +72,14 @@ const golden: string[] = [
...
+        const sources: Source[] = [
+            { code: code, path: "<unknown>", origin: "user" },
+        ];
         let ctx = openContext(
             new CompilerContext(),
-            [{ code: code, path: "<unknown>", origin: "user" }],
+            sources,
             [],
-            getParser(ast),
+            parseModules(sources, getParser(ast)),
```
Comment (verytactical) [inline src/generator/writers/writeExpression.spec.ts:82]: Pleasure to my eyes :heart:

**Review by verytactical — DISMISSED** [review]

File: src/ast/generated/gen-make-functions-script.ts (hunk 6 above)
Comment (jeshecdom) [reply src/ast/generated/gen-make-functions-script.ts]: I did not fully understand the comment. However, I changed all direct type comparisons to calls for their corresponding guard function `t.isX` (with only one exception in the switch case for `TSTupleType` in function `qualifyType`, for which I added a comment in the code).

File: src/ast/generated/gen-make-functions-script.ts (hunk 5 above)
Comment (jeshecdom) [reply src/ast/generated/gen-make-functions-script.ts]: Done

File: src/ast/generated/gen-make-functions-script.ts (hunk 7 above)
Comment (jeshecdom) [reply src/ast/generated/gen-make-functions-script.ts:302]: Done

File: src/ast/generated/gen-make-functions-script.ts (hunk 4 above)
Comment (jeshecdom) [reply src/ast/generated/gen-make-functions-script.ts]: Done

File: package.json (hunk 3 above)
Comment (jeshecdom) [reply package.json]: Done
