### PR TITLE
fix(codegen): save contract state on early return in receivers

### LINKED ISSUE #2461: Early `return` statements in receivers must invoke contract state saves
The following example should increment `x` after calling the empty receiver, but, in fact, the contract state never changes:

```tact
contract Foo(x: Int) {
  receive() {
    if (true) {
      x += 1;
      return;
    }
  }
}
```

### PR DESCRIPTION
**Pull request by anton-trunov**
## Issue

Closes #2461.

## Checklist

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases

### CODE REVIEW

File: src/generator/writers/writeRouter.ts [hunk 1]
```diff
@@ -673,18 +669,43 @@ function writeReceiverBody(
...
+    );
     wCtx.append("return ();");
 }
 
+function storeContractVariablesConditionally(
+    rcvEffects: ReadonlySet<Effect>,
+    contract: TypeDescription,
+    wCtx: WriterContext,
+): string {
+    return enabledAlwaysSaveContractData(wCtx.ctx) ||
```
Comment (Kaladin13) [inline src/generator/writers/writeRouter.ts:689]: I understand that this is hack for now, but maybe let's break this 3-conditional ternary operator into few variables or add comments? 

Really hard to grasp what's happening here, especially with empty string as stub

**Review by Kaladin13 — DISMISSED** [review]
Everything good, comment on ternary operator

**Review by i582 — APPROVED** [review]

File: src/generator/writers/writeRouter.ts (hunk 1 above)
Comment (anton-trunov) [reply src/generator/writers/writeRouter.ts:689]: added a comment
