### PR TITLE
Compiler error on incorrect `address()` input

### LINKED ISSUE #354: Missing compiler error on incorrect `Address` value
```
import "@stdlib/deploy";

contract SampleTactContract with Deployable {
    init() {
    }
    get fun test_address(): Address {
        let a1: Address = address("FQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N");
        return a1;
    }
}
```

Got:
```
💼 Compiling project sample...
   > SampleTactContract: tact compiler
Tact compilation failed
Error: Invalid checksum: FQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N
    at parseFriendlyAddress (node_modules/@ton/core/dist/address/Address.js:34:15)
    at Address.parseFriendly (node_modules/@ton/core/dist/address/Address.js:127:21)
    at Address.parse (node_modules/@ton/core/dist/address/Address.js:102:25)
    at Object.generate (dist/abi/global.js:95:48)
    at writeExpression (dist/generator/writers/writeExpression.js:481:57)
    at writeCastedExpression (dist/generator/writers/writeFunction.js:19:77)
    at writeStatement (dist/generator/writers/writeFunction.js:85:99)
    at dist/generator/writers/writeFunction.js:410:17
    at WriterContext.body (dist/generator/Writer.js:186:9)
    at dist/generator/writers/writeFunction.js:398:13
💥 Compilation failed. Skipping packaging
```

Expected: a readable compiler error.

### PR DESCRIPTION
**Pull request by Gusarich**
Closes #354 

- [x] I have updated CHANGELOG.md
- [x] I have added tests to demonstrate the contribution is correctly implemented: this usually includes both positive and negative tests, showing the happy path(s) and featuring intentionally broken cases
- [x] I have run all the tests locally and no test failure was reported
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/abi/global.ts [hunk 1]
```diff
@@ -100,7 +100,12 @@ export const GlobalFunctions: Map<string, AbiFunction> = new Map([
                     resolved[0],
                     ctx.ctx,
                 ) as string;
-                const address = Address.parse(str);
+                let address: Address;
+                try {
+                    address = Address.parse(str);
+                } catch {
+                    throwError(`Address ${str} invalid address`, ref);
```
Comment (anton-trunov) [inline src/abi/global.ts]:
```suggestion
                    throwError(`${str} is not a valid address`, ref);
```

File: src/test/feature-address.spec.ts [hunk 2]
```diff
@@ -26,4 +40,15 @@ describe("feature-address", () => {
...
         );
     });
+
+    it("should not compile with uninitialized storage fields", async () => {
+        const result = await run({
+            configPath: __dirname + "/test-tact.config.json",
+            projectNames: ["invalid-address"],
+        });
+        expect((consoleLogger.error as jest.Mock).mock.lastCall[0]).toContain(
+            "Address FQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N invalid address",
```
Comment (anton-trunov) [inline src/test/feature-address.spec.ts]:
```suggestion
            "FQCD39VS5jcptHL8vMjEXrzGaRcCVYto7HUn4bpAOg8xqB2N is not a valid address",
```

**Review by anton-trunov — DISMISSED** [review]

**Review by anton-trunov — APPROVED** [review]
