### PR TITLE
fix: better attribute error message

### LINKED ISSUE #1255: Attributes don't have locations
Function and constant attributes are represented as strings in AST. In order to emit error that involves an attribute, there is no way to gets its location.

Attributes should be represented as objects.

```
type AstFooAttribute = {
    kind: 'foo';
    loc: SrcInfo;
}
```

### PR DESCRIPTION
**Pull request by verytactical**
## Issue

Closes #1255.

## Checklist

- [ ] I have updated CHANGELOG.md
- [x] I have run all the tests locally and no test failure was reported
- [x] I have run the linter, formatter and spellchecker
- [x] I did not do unrelated and/or undiscussed refactorings

### CODE REVIEW

File: src/grammar/next/index.ts [hunk 1]
```diff
@@ -1063,7 +1064,10 @@ const parseConstantDef =
     };
 
 const parseConstant =
-    (node: $ast.Constant): Handler<A.AstConstantDecl | A.AstConstantDef> =>
+    (
+        node: $ast.Constant,
+        noAttributes: boolean = false,
```
Comment (novusnota) [inline src/grammar/next/index.ts]: default value spotted

File: src/grammar/next/__snapshots__/grammar.spec.ts.snap
Comment (anton-trunov) [inline src/grammar/next/__snapshots__/grammar.spec.ts.snap:1]: Do we have tests with duplicate constant attributes in contracts/traits?

**Review by anton-trunov — APPROVED** [review]
