### PR TITLE
fix: separate wildcard from id

### LINKED ISSUE #2433: Make wildcard (`_`) a separate AST node
Right now, it's implemented as an `AstId` with the `"_"` text.

### PR DESCRIPTION
**Pull request by verytactical**
Closes https://github.com/tact-lang/tact/issues/2433

### CODE REVIEW

File: src/ast/getAstSchema.ts [hunk 1]
```diff
@@ -277,7 +277,7 @@ export const getAstSchema = (
             }),
         StatementDestruct: (
             type: Ast.TypeId,
-            identifiers: Map<string, [Ast.Id, Ast.Id]>,
+            identifiers: Map<string, [Ast.Id, Ast.Id | Ast.Wildcard]>,
```
Comment (anton-trunov) [inline src/ast/getAstSchema.ts]:
```suggestion
            identifiers: Map<string, [Ast.Id, Ast.OptionalId]>,
```

File: src/ast/getAstSchema.ts [hunk 2]
```diff
@@ -382,7 +382,7 @@ export const getAstSchema = (
             statements: Ast.Statement[],
             loc: Loc,
             catchBlock?: {
-                catchName: Ast.Id;
+                catchName: Ast.Id | Ast.Wildcard;
```
Comment (anton-trunov) [inline src/ast/getAstSchema.ts]:
```suggestion
                catchName: Ast.OptionalId;
```
